/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.eqcoin.avro;

@org.apache.avro.specific.AvroGenerated
public interface EQCHiveSyncNetwork {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"EQCHiveSyncNetwork\",\"namespace\":\"org.eqcoin.avro\",\"types\":[{\"type\":\"record\",\"name\":\"O\",\"fields\":[{\"name\":\"o\",\"type\":\"bytes\"}]}],\"messages\":{\"registerSP\":{\"request\":[{\"name\":\"S\",\"type\":\"O\"}],\"response\":\"O\"},\"getSPList\":{\"request\":[{\"name\":\"F\",\"type\":\"O\"}],\"response\":\"O\"},\"getEQCHiveTail\":{\"request\":[],\"response\":\"O\"},\"getEQCHiveRootProof\":{\"request\":[{\"name\":\"H\",\"type\":\"O\"}],\"response\":\"O\"},\"getEQCHiveRoot\":{\"request\":[{\"name\":\"H\",\"type\":\"O\"}],\"response\":\"O\"},\"getEQCHive\":{\"request\":[{\"name\":\"H\",\"type\":\"O\"}],\"response\":\"O\"},\"getLockInfo\":{\"request\":[{\"name\":\"S\",\"type\":\"O\"}],\"response\":\"O\"}}}");
  /**
   */
  org.eqcoin.avro.O registerSP(org.eqcoin.avro.O S);
  /**
   */
  org.eqcoin.avro.O getSPList(org.eqcoin.avro.O F);
  /**
   */
  org.eqcoin.avro.O getEQCHiveTail();
  /**
   */
  org.eqcoin.avro.O getEQCHiveRootProof(org.eqcoin.avro.O H);
  /**
   */
  org.eqcoin.avro.O getEQCHiveRoot(org.eqcoin.avro.O H);
  /**
   */
  org.eqcoin.avro.O getEQCHive(org.eqcoin.avro.O H);
  /**
   */
  org.eqcoin.avro.O getLockInfo(org.eqcoin.avro.O S);

  @SuppressWarnings("all")
  public interface Callback extends EQCHiveSyncNetwork {
    public static final org.apache.avro.Protocol PROTOCOL = org.eqcoin.avro.EQCHiveSyncNetwork.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void registerSP(org.eqcoin.avro.O S, org.apache.avro.ipc.Callback<org.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getSPList(org.eqcoin.avro.O F, org.apache.avro.ipc.Callback<org.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getEQCHiveTail(org.apache.avro.ipc.Callback<org.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getEQCHiveRootProof(org.eqcoin.avro.O H, org.apache.avro.ipc.Callback<org.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getEQCHiveRoot(org.eqcoin.avro.O H, org.apache.avro.ipc.Callback<org.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getEQCHive(org.eqcoin.avro.O H, org.apache.avro.ipc.Callback<org.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getLockInfo(org.eqcoin.avro.O S, org.apache.avro.ipc.Callback<org.eqcoin.avro.O> callback) throws java.io.IOException;
  }
}