/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.eqcoin.avro;

@org.apache.avro.specific.AvroGenerated
public interface EQCMinerNetwork {
  public static final org.eqcoin.rpc.gateway.Gateway PROTOCOL = org.apache.avro.Gateway.parse("{\"protocol\":\"EQCMinerNetwork\",\"namespace\":\"org.eqcoin.avro\",\"types\":[{\"type\":\"record\",\"name\":\"O\",\"fields\":[{\"name\":\"o\",\"type\":\"bytes\"}]}],\"messages\":{\"registerSP\":{\"request\":[{\"name\":\"S\",\"type\":\"O\"}],\"response\":\"O\"},\"getSPList\":{\"request\":[{\"name\":\"F\",\"type\":\"O\"}],\"response\":\"O\"},\"broadcastNewEQCHive\":{\"request\":[{\"name\":\"E\",\"type\":\"O\"}],\"response\":\"O\"}}}");
  /**
   */
  org.eqcoin.avro.O registerSP(org.eqcoin.avro.O S);
  /**
   */
  org.eqcoin.avro.O getSPList(org.eqcoin.avro.O F);
  /**
   */
  org.eqcoin.avro.O broadcastNewEQCHive(org.eqcoin.avro.O E);

  @SuppressWarnings("all")
  public interface Callback extends EQCMinerNetwork {
    public static final org.eqcoin.rpc.gateway.Gateway PROTOCOL = org.eqcoin.avro.EQCMinerNetwork.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void registerSP(org.eqcoin.avro.O S, org.apache.avro.ipc.Callback<org.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getSPList(org.eqcoin.avro.O F, org.apache.avro.ipc.Callback<org.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void broadcastNewEQCHive(org.eqcoin.avro.O E, org.apache.avro.ipc.Callback<org.eqcoin.avro.O> callback) throws java.io.IOException;
  }
}