/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.eqcoin.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface MinerNetwork {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"MinerNetwork\",\"namespace\":\"com.eqchains.avro\",\"types\":[{\"type\":\"record\",\"name\":\"O\",\"fields\":[{\"name\":\"o\",\"type\":\"bytes\"}]}],\"messages\":{\"ping\":{\"request\":[{\"name\":\"c\",\"type\":\"O\"}],\"response\":\"O\"},\"getMinerList\":{\"request\":[],\"response\":\"O\"},\"getFullNodeList\":{\"request\":[],\"response\":\"O\"},\"broadcastNewBlock\":{\"request\":[{\"name\":\"b\",\"type\":\"O\"}],\"response\":\"O\"},\"getTransactionIndexList\":{\"request\":[{\"name\":\"s\",\"type\":\"O\"}],\"response\":\"O\"},\"getTransactionList\":{\"request\":[{\"name\":\"transactionIndexList\",\"type\":\"O\"}],\"response\":\"O\"}}}");
  /**
   */
  com.eqcoin.avro.O ping(com.eqcoin.avro.O c) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqcoin.avro.O getMinerList() throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqcoin.avro.O getFullNodeList() throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqcoin.avro.O broadcastNewBlock(com.eqcoin.avro.O b) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqcoin.avro.O getTransactionIndexList(com.eqcoin.avro.O s) throws org.apache.avro.AvroRemoteException;
  /**
   */
  com.eqcoin.avro.O getTransactionList(com.eqcoin.avro.O transactionIndexList) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends MinerNetwork {
    public static final org.apache.avro.Protocol PROTOCOL = com.eqcoin.avro.MinerNetwork.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void ping(com.eqcoin.avro.O c, org.apache.avro.ipc.Callback<com.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getMinerList(org.apache.avro.ipc.Callback<com.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getFullNodeList(org.apache.avro.ipc.Callback<com.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void broadcastNewBlock(com.eqcoin.avro.O b, org.apache.avro.ipc.Callback<com.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getTransactionIndexList(com.eqcoin.avro.O s, org.apache.avro.ipc.Callback<com.eqcoin.avro.O> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void getTransactionList(com.eqcoin.avro.O transactionIndexList, org.apache.avro.ipc.Callback<com.eqcoin.avro.O> callback) throws java.io.IOException;
  }
}